# Generated by Django 3.0.3 on 2020-03-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='nofly',
            field=models.BooleanField(default=False),
        ),
    ]
