# Generated by Django 3.0.3 on 2020-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0002_auto_20200218_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
